name: Build and deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
env:
  WD_USERNAME: ${{ secrets.WD_USERNAME }}
  WD_PASSWORD: ${{ secrets.WD_PASSWORD }}
  APP_PATH: ${{ secrets.WD_USERNAME }}
  DEPLOY_SERIVICE_URL: nt37.unoeuro.com
  CS_PROJ: .\GamMaSite.csproj
  RUNTIME: win-x86
  FRAMEWORK: net6.0
  CONFIGURATION: Release
  SELF_CONTAINED: true
jobs:
  build-deploy:
    runs-on: windows-2022
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Add dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Variable substitutions
        uses: microsoft/variable-substitution@v1 
        with:
          files: 'appsettings.json'
        env:
          ConnectionStrings.DefaultConnection: ${{ secrets.CONNECTION_STRING }}
          EmailSender.UserName: ${{ secrets.MAILGUN_MAIL }}
          EmailSender.Password: ${{ secrets.MAILGUN_API_KEY }}
          SmsSender.ApiKey: ${{ secrets.SMS_APIGATEWAY_KEY }}
          StripeConfig.PublicApiKey: ${{ secrets.STRIPE_PUBLIC_API_KEY }}
          StripeConfig.SecretApiKey: ${{ secrets.STRIPE_SECRET_API_KEY }}
          GitHub.Token: ${{ secrets.GH_API_KEY }}
          GitLab.Token: ${{ secrets.GITLAB_API_KEY }}
      - name: Restore NuGet packages
        run: dotnet restore -r $env:RUNTIME $env:CS_PROJ
      - name: Build and release app
        run: >
          dotnet msbuild $env:CS_PROJ
          /p:Username=$env:WD_USERNAME /p:Password=$env:WD_PASSWORD
          /p:DeployIisAppPath=$env:APP_PATH /p:MSDeployServiceURL=$env:DEPLOY_SERIVICE_URL
          /p:RuntimeIdentifier=$env:RUNTIME /p:TargetFramework=$env:FRAMEWORK
          /p:Configuration=$env:CONFIGURATION /p:SelfContained=$env:SELF_CONTAINED
          /p:WebPublishMethod=MSDeploy /p:MSDeployPublishMethod=WMSVC
          /p:DeployOnBuild=true /p:EnableMSDeployBackup=true
          /p:EnableMsDeployAppOffline=true /p:SkipExtraFilesOnServer=false
