name: Build and deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
jobs:
  build-deploy:
    runs-on: windows-latest
    steps:
      - name: Check-out your repository
        uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build app for release
        run: msbuild .\GamMaSite.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
