name: Build and deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
env:
  WD_USERNAME: ${{ secrets.WD_USERNAME }}
  WD_PASSWORD: ${{ secrets.WD_PASSWORD }}
  IIS_PROFILE: .\Properties\PublishProfiles\IISProfile.pubxml
  CS_PROJ: .\GamMaSite.csproj
  RUNTIME: win-x86
  TARGET: net5.0
  DEPLOY_URL: nt37.unoeuro.com
jobs:
  build-deploy:
    runs-on: windows-latest
    steps:
      - name: Check-out your repository
        uses: actions/checkout@v2
      - name: Add dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Variable substitutions
        uses: microsoft/variable-substitution@v1 
        with:
          files: 'appsettings.json'
        env:
          ConnectionStrings.DefaultConnection: ${{ secrets.CONNECTION_STRING }}
          EmailSender.UserName: ${{ secrets.MAILGUN_MAIL }}
          EmailSender.Password: ${{ secrets.MAILGUN_API_KEY }}
          SmsSender.ApiKey: ${{ secrets.SMS_APIGATEWAY_KEY }}
          StripeConfig.PublicApiKey: ${{ secrets.STRIPE_PUBLIC_API_KEY }}
          StripeConfig.SecretApiKey: ${{ secrets.STRIPE_SECRET_API_KEY }}
          GitHub.Token: ${{ secrets.GH_API_KEY }}
          GitLab.Token: ${{ secrets.GITLAB_API_KEY }}
      - name: Restore NuGet packages
        shell: pwsh
        run: dotnet restore -r $env:RUNTIME $env:CS_PROJ
      - name: Build and release app
        shell: pwsh
        run: | 
          dotnet msbuild /p:Username=$env:WD_USERNAME /p:Password=$env:WD_PASSWORD $env:CS_PROJ \
          /p:RuntimeIdentifier=$env:RUNTIME /p:TargetFramework=$env:TARGET /p:MSDeployServiceURL=$env:DEPLOY_URL \
          /p:DeployIisAppPath=$env:WD_USERNAME /p:DeployOnBuild=true /p:MSDeployPublishMethod=WMSVC \
          /p:WebPublishMethod=MSDeploy /p:Configuration=Release /p:SelfContained=true \
          /p:SkipExtraFilesOnServer=true /p:EnableMSDeployBackup=true
