name: Build and deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
jobs:
  build-deploy:
    runs-on: windows-latest
    steps:
      - name: Check-out your repository
        uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Add dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Restore NuGet packages
        run: dotnet restore -r win-x86 .\GamMaSite.csproj
      - name: Build app for release
        run: dotnet msbuild .\GamMaSite.csproj /p:DeployOnBuild=true /p:PublishProfile=./Properties/PublishProfiles/IISProfile.pubxml /p:Username=$env:USERNAME /p:Password=$env:PASSWORD
