-- =========================================================
-- GAMMASITE FINANCE DATABASE
-- PostgreSQL / Supabase
-- =========================================================


-- =========================================================
-- 1. ACCOUNT
-- =========================================================

CREATE TABLE IF NOT EXISTS public.account (
    id text NOT NULL,
    main_account text,
    account_key bigint,
    sub_account text,
    sub_account_key bigint,
    context text,
    context_key bigint,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT account_pkey PRIMARY KEY (id)
);


-- =========================================================
-- 2. BANK ACCOUNT
-- =========================================================

CREATE TABLE IF NOT EXISTS public.bank_account (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    date date,
    text text,
    amount numeric(14, 2),
    balance numeric(14, 2),

    -- false = importeret
    -- true = manuelt oprettet
    is_manual boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT bank_account_pkey PRIMARY KEY (id)
);

-- Importerede bankposter skal være unikke på alle fire felter.
-- Manuelt oprettede poster må gerne have samme værdier.
CREATE UNIQUE INDEX IF NOT EXISTS ux_bank_account_business_key
ON public.bank_account (
    date,
    text,
    amount,
    balance
) NULLS NOT DISTINCT
WHERE is_manual = false;


-- =========================================================
-- 3. MOBILEPAY
-- =========================================================

CREATE TABLE IF NOT EXISTS public.mobilepay (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    date date,
    timestamp_iso timestamp without time zone,
    amount numeric(14, 2),
    message text,
    transaction_type text,
    transfer_ref text,
    transfer_date date,
    payment_tx_id text,
    payner_name text,

    -- false = importeret
    -- true = manuelt oprettet
    is_manual boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT mobilepay_pkey PRIMARY KEY (id)
);

-- Importerede MobilePay-poster skal være unikke på de seks felter.
-- Manuelt oprettede poster må gerne have samme værdier.
CREATE UNIQUE INDEX IF NOT EXISTS ux_mobilepay_business_key
ON public.mobilepay (
    timestamp_iso,
    amount,
    message,
    transaction_type,
    transfer_ref,
    payment_tx_id
) NULLS NOT DISTINCT
WHERE is_manual = false;


-- =========================================================
-- 4. POSTERING GROUP
-- =========================================================

CREATE TABLE IF NOT EXISTS public.postering_group (
    id text NOT NULL,
    posting_group text,
    context text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT postering_group_pkey PRIMARY KEY (id)
);


-- =========================================================
-- 5. FORECAST
-- =========================================================

CREATE TABLE IF NOT EXISTS public.forecast (
    id text NOT NULL,
    account_id text,
    postering_group_id text,
    year_actual integer,
    forecast numeric(14, 2),
    forecast_type text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT forecast_pkey PRIMARY KEY (id),

    CONSTRAINT forecast_account_fk
        FOREIGN KEY (account_id)
        REFERENCES public.account(id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,

    CONSTRAINT forecast_postering_group_fk
        FOREIGN KEY (postering_group_id)
        REFERENCES public.postering_group(id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


-- =========================================================
-- 6. POSTERINGER
-- =========================================================

CREATE TABLE IF NOT EXISTS public.posteringer (
    id text NOT NULL,
    date date,
    posting_date date,
    text text,
    amount numeric(14, 2),
    bank_account_key bigint,
    mp_key bigint,
    user_id text,
    account_number text,
    posting_group_id text,
    document text,
    posterings_date date,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT posteringer_pkey PRIMARY KEY (id),

    CONSTRAINT posteringer_bank_account_fk
        FOREIGN KEY (bank_account_key)
        REFERENCES public.bank_account(id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,

    CONSTRAINT posteringer_mobilepay_fk
        FOREIGN KEY (mp_key)
        REFERENCES public.mobilepay(id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,

    CONSTRAINT posteringer_account_fk
        FOREIGN KEY (account_number)
        REFERENCES public.account(id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,

    CONSTRAINT posteringer_postering_group_fk
        FOREIGN KEY (posting_group_id)
        REFERENCES public.postering_group(id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


-- =========================================================
-- 7. INDEXES
-- =========================================================

CREATE INDEX IF NOT EXISTS ix_forecast_account_id
ON public.forecast(account_id);

CREATE INDEX IF NOT EXISTS ix_forecast_postering_group_id
ON public.forecast(postering_group_id);

CREATE INDEX IF NOT EXISTS ix_forecast_year_actual
ON public.forecast(year_actual);

CREATE INDEX IF NOT EXISTS ix_posteringer_bank_account_key
ON public.posteringer(bank_account_key);

CREATE INDEX IF NOT EXISTS ix_posteringer_mp_key
ON public.posteringer(mp_key);

CREATE INDEX IF NOT EXISTS ix_posteringer_user_id
ON public.posteringer(user_id);

CREATE INDEX IF NOT EXISTS ix_posteringer_account_number
ON public.posteringer(account_number);

CREATE INDEX IF NOT EXISTS ix_posteringer_posting_group_id
ON public.posteringer(posting_group_id);

CREATE INDEX IF NOT EXISTS ix_posteringer_date
ON public.posteringer(date);

CREATE INDEX IF NOT EXISTS ix_posteringer_posting_date
ON public.posteringer(posting_date);

-- =========================================================
-- 8. IMPORT HISTORY / LATEST IMPORT STATUS
-- =========================================================

CREATE TABLE IF NOT EXISTS public.import_history (
    import_type text NOT NULL,
    imported_at timestamp with time zone NOT NULL,
    file_name text,
    status text NOT NULL DEFAULT 'completed',
    rows_processed integer NOT NULL DEFAULT 0,
    rows_inserted integer NOT NULL DEFAULT 0,
    rows_updated integer NOT NULL DEFAULT 0,
    rows_requiring_review integer NOT NULL DEFAULT 0,
    notes text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT import_history_pkey PRIMARY KEY (import_type),
    CONSTRAINT import_history_status_check
        CHECK (status IN ('completed', 'partial', 'failed')),
    CONSTRAINT import_history_counts_check
        CHECK (
            rows_processed >= 0
            AND rows_inserted >= 0
            AND rows_updated >= 0
            AND rows_requiring_review >= 0
        )
);

-- =========================================================
-- 9. TIMESTAMPS / UPDATED-AT TRIGGERS
-- =========================================================

ALTER TABLE public.account ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.account ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.bank_account ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.bank_account ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.mobilepay ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.mobilepay ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.postering_group ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.postering_group ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.forecast ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.forecast ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.posteringer ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.posteringer ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.posteringer ADD COLUMN IF NOT EXISTS posting_date date;
UPDATE public.posteringer
SET posting_date = COALESCE(posting_date, posterings_date, date)
WHERE posting_date IS NULL;
ALTER TABLE public.import_history ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.import_history ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS account_set_updated_at ON public.account;
CREATE TRIGGER account_set_updated_at BEFORE UPDATE ON public.account FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS bank_account_set_updated_at ON public.bank_account;
CREATE TRIGGER bank_account_set_updated_at BEFORE UPDATE ON public.bank_account FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS mobilepay_set_updated_at ON public.mobilepay;
CREATE TRIGGER mobilepay_set_updated_at BEFORE UPDATE ON public.mobilepay FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS postering_group_set_updated_at ON public.postering_group;
CREATE TRIGGER postering_group_set_updated_at BEFORE UPDATE ON public.postering_group FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS forecast_set_updated_at ON public.forecast;
CREATE TRIGGER forecast_set_updated_at BEFORE UPDATE ON public.forecast FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS posteringer_set_updated_at ON public.posteringer;
CREATE TRIGGER posteringer_set_updated_at BEFORE UPDATE ON public.posteringer FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS import_history_set_updated_at ON public.import_history;
CREATE TRIGGER import_history_set_updated_at BEFORE UPDATE ON public.import_history FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =========================================================
-- 10. ROW LEVEL SECURITY
-- =========================================================

ALTER TABLE public.account ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bank_account ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.forecast ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mobilepay ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.postering_group ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posteringer ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.import_history ENABLE ROW LEVEL SECURITY;


-- =========================================================
-- 11. BLOCK DIRECT API ACCESS
-- =========================================================

REVOKE ALL ON TABLE public.account FROM anon, authenticated;
REVOKE ALL ON TABLE public.bank_account FROM anon, authenticated;
REVOKE ALL ON TABLE public.forecast FROM anon, authenticated;
REVOKE ALL ON TABLE public.mobilepay FROM anon, authenticated;
REVOKE ALL ON TABLE public.postering_group FROM anon, authenticated;
REVOKE ALL ON TABLE public.posteringer FROM anon, authenticated;
REVOKE ALL ON TABLE public.import_history FROM anon, authenticated;
