-- =========================================================
-- GAMMASITE FINANCE DATABASE
-- PostgreSQL / Supabase
-- =========================================================


-- =========================================================
-- 1. ACCOUNT
-- =========================================================

CREATE TABLE IF NOT EXISTS public.account (
    id text NOT NULL,
    main_account text,
    account_key bigint,
    sub_account text,
    sub_account_key bigint,
    context text,
    context_key bigint,

    CONSTRAINT account_pkey PRIMARY KEY (id)
);


-- =========================================================
-- 2. BANK ACCOUNT
-- =========================================================

CREATE TABLE IF NOT EXISTS public.bank_account (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    date date,
    text text,
    amount numeric(14, 2),
    balance numeric(14, 2),

    -- false = importeret
    -- true = manuelt oprettet
    is_manual boolean NOT NULL DEFAULT false,

    CONSTRAINT bank_account_pkey PRIMARY KEY (id)
);

-- Importerede bankposter skal være unikke på alle fire felter.
-- Manuelt oprettede poster må gerne have samme værdier.
CREATE UNIQUE INDEX IF NOT EXISTS ux_bank_account_business_key
ON public.bank_account (
    date,
    text,
    amount,
    balance
) NULLS NOT DISTINCT
WHERE is_manual = false;


-- =========================================================
-- 3. MOBILEPAY
-- =========================================================

CREATE TABLE IF NOT EXISTS public.mobilepay (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    date date,
    timestamp_iso timestamp without time zone,
    amount numeric(14, 2),
    message text,
    transaction_type text,
    transfer_ref text,
    transfer_date date,
    payment_tx_id text,
    payner_name text,

    -- false = importeret
    -- true = manuelt oprettet
    is_manual boolean NOT NULL DEFAULT false,

    CONSTRAINT mobilepay_pkey PRIMARY KEY (id)
);

-- Importerede MobilePay-poster skal være unikke på de seks felter.
-- Manuelt oprettede poster må gerne have samme værdier.
CREATE UNIQUE INDEX IF NOT EXISTS ux_mobilepay_business_key
ON public.mobilepay (
    timestamp_iso,
    amount,
    message,
    transaction_type,
    transfer_ref,
    payment_tx_id
) NULLS NOT DISTINCT
WHERE is_manual = false;


-- =========================================================
-- 4. POSTERING GROUP
-- =========================================================

CREATE TABLE IF NOT EXISTS public.postering_group (
    id text NOT NULL,
    posting_group text,
    context text,

    CONSTRAINT postering_group_pkey PRIMARY KEY (id)
);


-- =========================================================
-- 5. FORECAST
-- =========================================================

CREATE TABLE IF NOT EXISTS public.forecast (
    id text NOT NULL,
    account_id text,
    postering_group_id text,
    year_actual integer,
    forecast numeric(14, 2),
    forecast_type text,

    CONSTRAINT forecast_pkey PRIMARY KEY (id),

    CONSTRAINT forecast_account_fk
        FOREIGN KEY (account_id)
        REFERENCES public.account(id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,

    CONSTRAINT forecast_postering_group_fk
        FOREIGN KEY (postering_group_id)
        REFERENCES public.postering_group(id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


-- =========================================================
-- 6. POSTERINGER
-- =========================================================

CREATE TABLE IF NOT EXISTS public.posteringer (
    id text NOT NULL,
    date date,
    posting_date date,
    text text,
    amount numeric(14, 2),
    bank_account_key bigint,
    mp_key bigint,
    user_id text,
    account_number text,
    posting_group_id text,
    document text,
    belongs_to_last_year boolean,
    posterings_date date,

    CONSTRAINT posteringer_pkey PRIMARY KEY (id),

    CONSTRAINT posteringer_bank_account_fk
        FOREIGN KEY (bank_account_key)
        REFERENCES public.bank_account(id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,

    CONSTRAINT posteringer_mobilepay_fk
        FOREIGN KEY (mp_key)
        REFERENCES public.mobilepay(id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,

    CONSTRAINT posteringer_account_fk
        FOREIGN KEY (account_number)
        REFERENCES public.account(id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,

    CONSTRAINT posteringer_postering_group_fk
        FOREIGN KEY (posting_group_id)
        REFERENCES public.postering_group(id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


-- =========================================================
-- 7. INDEXES
-- =========================================================

CREATE INDEX IF NOT EXISTS ix_forecast_account_id
ON public.forecast(account_id);

CREATE INDEX IF NOT EXISTS ix_forecast_postering_group_id
ON public.forecast(postering_group_id);

CREATE INDEX IF NOT EXISTS ix_forecast_year_actual
ON public.forecast(year_actual);

CREATE INDEX IF NOT EXISTS ix_posteringer_bank_account_key
ON public.posteringer(bank_account_key);

CREATE INDEX IF NOT EXISTS ix_posteringer_mp_key
ON public.posteringer(mp_key);

CREATE INDEX IF NOT EXISTS ix_posteringer_user_id
ON public.posteringer(user_id);

CREATE INDEX IF NOT EXISTS ix_posteringer_account_number
ON public.posteringer(account_number);

CREATE INDEX IF NOT EXISTS ix_posteringer_posting_group_id
ON public.posteringer(posting_group_id);

CREATE INDEX IF NOT EXISTS ix_posteringer_date
ON public.posteringer(date);

CREATE INDEX IF NOT EXISTS ix_posteringer_posting_date
ON public.posteringer(posting_date);

-- =========================================================
-- 8. ROW LEVEL SECURITY
-- =========================================================

ALTER TABLE public.account ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bank_account ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.forecast ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mobilepay ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.postering_group ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posteringer ENABLE ROW LEVEL SECURITY;


-- =========================================================
-- 9. BLOCK DIRECT API ACCESS
-- =========================================================

REVOKE ALL ON TABLE public.account FROM anon, authenticated;
REVOKE ALL ON TABLE public.bank_account FROM anon, authenticated;
REVOKE ALL ON TABLE public.forecast FROM anon, authenticated;
REVOKE ALL ON TABLE public.mobilepay FROM anon, authenticated;
REVOKE ALL ON TABLE public.postering_group FROM anon, authenticated;
REVOKE ALL ON TABLE public.posteringer FROM anon, authenticated;
